### ISSUE TITLE
Add support for Ukraine TIN

### ISSUE THREAD

**Issue by unho** [arthurdejong/python-stdnum#117]
It is called "ІНПП" (short for "Ідентифікаційний номер платника податків") and depending on the source it is either 10 or 12 digits long (update: this is because they are referring to two different numbers).

* https://uk.m.wikipedia.org/wiki/Податковий_номер
  * Provides much clarity on the plurality of numbers.
  * (link from the Wikipedia page above) https://uk.m.wikipedia.org/wiki/Індивідуальний_податковий_номер_платника_ПДВ provides more data on one of those numbers (Індивідуальний податковий номер).
  * (another link from the Wikipedia page above) https://uk.wikipedia.org/wiki/Код_ЄДРПОУ provides data on other of those numbers (ЄДРПОУ), including link to algorithm. Also this number seems to be embedded in the "Індивідуальний податковий номер" number (previous line link).
    * Algorithm: http://1cinfo.com.ua/Articles/Proverka_koda_po_EDRPOU.aspx
* https://wiki.scn.sap.com/wiki/display/CRM/Ukraine
* https://en.wikipedia.org/wiki/VAT_identification_number#VAT_numbers_of_non-EU_countries
* http://world.salestaxhandbook.com/ua-ukraine

After plenty of reading the situation is this:
* For companies it is a 12 digit number, the first 7 digits being the EDRPOU without the check digit. Structure described in https://uk.wikipedia.org/wiki/Індивідуальний_податковий_номер_платника_ПДВ
* For people it is a 10 digit number called РНОКПП (RNOKPP). The following link includes explanation of structure and algorithm for the check digit: https://uk.wikipedia.org/wiki/Реєстраційний_номер_облікової_картки_платника_податків

Implementations:
* Python implementation for EDRPOU: https://github.com/pablissimo77/edrpou-iin-validation
* Javascript implementation: https://github.com/alazurenko/validate-edrpou

EDRPOU examples (more can be found searching on the Internet):
> 20551088
26112972
32855961
33499803
38004897
40109173
00032945
02224548
02363072
14282829
20551088
26112972
32855961
33499803
38004897
40109173
20077720
01566117
37958419
13956473
38243641
42485471
00493706
23541342
39434500
32161160
38168926
21705897
39308149
38149966
14282338
39896543
34868595
05460344
21045573
37107050
32523934
20022334
03359658
01497439
00497006
14352406
* EDRPOU examples from https://zakupki.prom.ua/en/gov/tenders (I have stopped in page 5)
> 01991116
34827358
26615223
08027576
05387179
41810109
02070812
23505151
01996272
32359108
41475043
24978555
14310299
41800368
39816845
40081200
02070812
40046124
02145010
04375151
01984613
00692009
08183359
02910108
01984613
04350665
02070950
03355353
24976272
04014246
21726250
08803543
02066769
02145010
07904041
01986380
02066769
02142448
08564794
14307529
02147606
02142448
08563808
* EDRPOU examples from http://www.uafin.net/reestr.php (only the first two pages)
> 38572374
38203737
32277963
36297353
35264255
36041214
41617928
34275671
43629317
31394728
42309535
43529818
43178370
30998764
39738364
43586656
43618792
38516938
31867274
38066005
35622956
32355213
36383349
32610639
34201058
37324614
41399586
31850889
30638956
33124015
00372109
32737851
30327425
35623077
30702701
05489555
43476227
43518172
* EDRPOU examples from http://www.bmkik.hu/download.php?id=1706
> 38775688
37609984
39034697
37181129
* EDRPOU examples from https://report2018.uz.gov.ua/en/Dodatki.php
> 00659101
01056273
00740599
00480247
00282406
00282435
00260652
13915014
30674235
32000106
19350062
13857564
42588390
42598807
* EDRPOU examples from https://tender.uub.com.ua/top-100-customers
> 02426097
02909938
02909996
02910031
02910060
03338030
03346822
03356128
03356571
03361661
03361678
03361780
03491079
03491085
03491180
03491300
03491406
03491435
03499945
04013755
04059243
05379487
05396638
08571363
13986712
20001303
20001585
20001591
20001823
20003749
20442705
22518134
22530614
22800735
22815333
23226362
23293513
24283333
25042882
25836018
26255795
26510514
31584378
31725604
34334305
34837504
36521731
36598008
37199618
37451388
37508470
37533381
37567646
37819430
37951998
37988155
38337116
39292197
39393260
39592941
39736985
40081221
40081237
40108625
40108866
40109173
41436842
42258617
42262749
00022438
00022496
00022504
00022585
00022651
00022680
00034022
00034051
00100227
00130694
00130725
00130926
00131564
00131587
00131819
00131954
01072609
01192220
01566330
02010669
02010758
02010830
02011261
02070766
02070987
02125102
02125237
02125266
02136554
02139133
02139771
* EDRPOU examples from http://pat.ua/reestr.php (only the first page):
> 20488297
05465672
05786100
01881876
36177661
00217857
01415559
00308778
00849184
00443074
14038383
02573817
23935584
00290280
03293304
14307481
03114017
04824652
00132003
00231610

* RNOKPP examples:
> 2985319296
1521251251
2199602758
2511313590
2464921030
2467920538
2979904457
2886719190
2521601845
3130600734
2940813715
2862500663
3279114362
* RNOKPP examples from http://www.ftu.org.ua/libs/spaw2/uploads/docs2/protokol_prezydia_3_2015_06_10.pdf
> 2517305837
2526400856
2881507890
2725020233
2019304211
3124313135
2687602513
2340714291
25 30 41 40 71
2661314935
2355207831
2531310373
2525808071
2071907598
2495912135
2595704439
2656501477
2507300273
3047924216
* RNOKPP examples from https://www.vmr.gov.ua/Docs/ExecutiveCommitteeDecisions/2019/%E2%84%96661%2014-03-2019.pdf
> 2777606331
2062412328
2514219625
2029212006
3190607860
2491109768
2849507907
2767507288
2431516896
2715212635
3132220152
2668604464
3152909256
2976609691
3323805078
3039702911
2803909085
2522615927
2618103132
2141715084
2223820028
2432915368
3104807458
2057604994
2511615015
2182917600
* RNOKPP examples from https://e-services.davr.gov.ua/site/find?dp-1-page=187&sort=wateruser_name&page=22&per-page=10
> 2358623466
2548903136
1941106083
2050823598
2221604457
2756824294
3099517368
2278520212
2215911880
* RNOKPP examples from https://mtu.gov.ua/files/Dok_NORMATUVKA/%D0%9D174.pdf
> 2200300272
2518609656
2360711297
1759013776
2162316775
2288012353
2360803036
2288012353
3215016793
2537610987
2981410717
2468920144
2986715322
2796607557
3104911417
2451902259
2427616997
* RNOKPP examples from https://oblrada.dp.gov.ua/wp-content/uploads/2019/12/%D0%94%D0%9E%D0%94%D0%90%D0%A2%D0%9E%D0%9A-2-%D0%9E%D0%A0%D0%95%D0%9D%D0%94%D0%902-1.docx
> 2166209127
3072814835
2323000531
2756915742
2735321158
3121614071
2446410726
3065520146
3451517675
3171718420
3022512606
3366800663
2722600497
2492601451
3087300101
2492810092

* ІНПП examples (continue looking for more examples in https://www.google.com/search?q=site:.ua+%22Individual+tax+number%22&start=120):
> VAT TAX Code ID: 139564716035
ІPN 004937026501
IIN: 381689212128
Individual tax number: 142823326578
IPN 004970016014
TIN 348685908161
TIN 143524004022
Individual tax number 402836426512
Individual Tax Number 216773326655
Individual tax number 020708509155
300198026656
000390026655
Individual Tax Number: 033571623012
ІPN 380572113073
ІPN 347716526585
ІPN 011161304633
IPN 360395026581
Individual tax number	266273426598
Individual Tax Number: 323482426593
Individual Tax Number 406953226590
Individual Tax Number: 300590610135
Individual tax number	143615726657
Individual tax number 325957526572
Individual tax number: 401693226540
Individual Tax Number: 215234726140
Individual Tax Number: 033571623012
Individual tax number 135079105817
Individual tax number 336319326512
Individual Tax Number: 376526526538
Individual tax number 004856713075
Individual tax number of the legal entity: 046531426533
Individual tax number 388008526576
Individual tax number 363711420363
Individual Tax Number 362858326507
Individual tax number: 015276926580
Individual tax number 004937026501
Individual tax number: 363011726537
IPN (individual tax number) 407035115535
Individual Tax Number 391757326557
Individual tax number 020709426654
Individual tax number: 403688026505
Individual tax number: 343811515534 
Individual tax number: 303765815534
Individual tax number: 020708926107
Individual tax number: 372192326516
Individual tax number 054607925261

**Comment by unho** [comment]
@arthurdejong I have created a PR with implementations for both ЄДРПОУ and РНОКПП, but I have been unable to find any description of the algorithm to verify ІНПП. Should we leave ІНПП unimplemented until more information is found or verify it is 12 digits long?

**Comment by unho** [comment]
@arthurdejong I am not sure if you closing the issue means that we will go without ІНПП.

**Comment by arthurdejong** [comment]
@unho Sorry, I missed that but according to https://uk.wikipedia.org/wiki/РНОКПП (and Google Translate) ІПН (іноді помилково вживається абревіатура) is the old name for the РНОКПП. I'm not sure ІПН and ІНПП are the same thing though. It may be a good idea to create a separate issue for the Ukrainian ІНПП if it is still useful.

**Comment by unho** [comment]
Honestly I have no idea about these numbers. It would be great if some ukrainian person could help us.
