### ISSUE TITLE
Add support for Thailand TIN

### ISSUE THREAD

**Issue by unho** [arthurdejong/python-stdnum#118]
It is called เลขประจำตัวผู้เสียภาษีอากร and it is 13 digits, like  1-2345-67890-12-3 (as figured out from an online PDF form from Thai Revenue Department https://www.rd.go.th )

* https://wiki.scn.sap.com/wiki/display/CRM/Thailand
* Format https://whtsvs.rd.go.th/WHTSVS/view/svsr/svsr044_6c
* https://msnagroup.com/new-thai-tax-id-number/

Search
* Search online (didn't test): http://www.thainaturecure.com/PIN/TIN.php
* API to check (looks good as it is from the Revenue Department and has some docs) http://www.rd.go.th/publish/42533.0.html

Examples:
* Found on the Internet:
  > 1 2345 45678 78 9
0107537001510
0107537001706
0105-515-004-336
099-4-00018994-0
0735560003739
0205560014832
0105556075980
0105551082333
0993000132246
0115562002441
0105552074946
0993000285042
0105555187377
099 4 00016542 1
0105560194629
0745555004781
0-1055-56187-72-9
0105534104171
0105555187377
084 555 3002144
0105555058364
3100700716215
0-1055-5408-2466
0735555000328
0-1055-51024-58-9
0-7455-57002-60-3
1015552076183

**Comment by unho** [comment]
@piruin Great job. Just a nit, how is it spelled "Memorandum of Association Number" in Thai? I guess it is not เลขประจำตัวผู้เสียภาษีอากร.

**Comment by piruin** [comment]
@unho 

"Memorandum of Association Number"  is  **เลขที่หนังสือบริคณห์สนธิ** in Thai. 
The acronym is  **บค**  but I'm not so sure because we commonly use `VAT` instead of `MOA`

**Comment by unho** [comment]
> "Memorandum of Association Number" is เลขที่หนังสือบริคณห์สนธิ in Thai.
The acronym is บค but I'm not so sure because we commonly use TIN instead of MOA

@piruin Are `TIN` and `MOA` the same thing in Thailand?

**Comment by piruin** [comment]
`MOA` is identification for company Issued by the **Department of Business Development**.
This number consists of 13 digits which the last is a check digit follow
the Personal Identity Number (PIN) standard. but with a different grouping format and always start with zero to indicate that is 13 digits number issued by DBD. like 0-XX-X-XXX-XXXXX-X.

**Thai Revenue Department** uses `MOA` as  `เลขประจำตัวผู้เสียภาษีอากร (TIN)` for companies.

**Comment by unho** [comment]
@arthurdejong Any chance we get a release soon? That would be much appreciated.
