### ISSUE TITLE
Add validation for South Africa phone numbers

### ISSUE THREAD

**Issue by unho** [arthurdejong/python-stdnum#130]
Regexes in http://regexlib.com/Search.aspx?k=south+africa

**Comment by arthurdejong** [comment]
There is already the very complete [phonenumbers](https://pypi.org/project/phonenumbers/) module that has very extensive support for checking phone numbers of various countries so I do not plan to add support for checking phone numbers to `python-stdnum` at this time. Keeping a database of phone numbers up-to-date is also far from trivial.
