### ISSUE TITLE
de.handelsregisternummer._to_min() reduces too many chars

### ISSUE THREAD

**Issue by kkaiser** [arthurdejong/python-stdnum#136]
The [`_to_min()` function in `de.handelsregisternummer`](https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/de/handelsregisternummer.py#L214) reduces both Hamburg and Homburg to the same court (key for Hamburg is overwritten in `_courts`) that is then returned from the validate function.

```python
In [1]: from stdnum.de.handelsregisternummer import _to_min, validate

In [2]: _to_min('Hamburg')
Out[2]: 'hmbrg'

In [3]: _to_min('Homburg')
Out[3]: 'hmbrg'

In [4]: validate('Hamburg HRA 61755')
Out[4]: 'Homburg HRA 61755'

In [5]: def _to_min(court):
    ...:     """Convert the court name for quick comparison without encoding issues."""
    ...:     return ''.join(
    ...:         x for x in court.lower()
    ...: if x in 'abcdefghijklmnopqrstvwxyz')
    ...:

In [6]: _to_min('Homburg')
Out[6]: 'hombrg'

In [7]: _to_min('Hamburg')
Out[7]: 'hambrg'
```

If there is a problem with encoding issues for "äöüß" you could maybe consider [unidecode](https://pypi.org/project/Unidecode/) or just make an exception for these two, I guess you know best.

**Comment by arthurdejong** [comment]
Thanks for your report. This was fixed in 51e00da. The reason that the code is a bit complex is that it tries to work around all kinds of encoding issues and also has to work with Python 2.6, 2.7 and Python 3.

Anyway, thanks for spotting this and reporting the issue.
