### ISSUE TITLE
Add support for Japan TIN number

### ISSUE THREAD

**Issue by unho** [arthurdejong/python-stdnum#142]
As explained in some of the links below Japan's Corporate Number is 13 digit long, where the first digit is the check digit for the trailing 12 digits.

* https://www.oecd.org/tax/automatic-exchange/crs-implementation-and-assistance/tax-identification-numbers/Japan-TIN.pdf
* https://en.wikipedia.org/wiki/Corporate_Number
* Official site on Corporate Number (includes online search) http://www.houjin-bangou.nta.go.jp/en/
* https://toma.co.jp/blog/jtg/do-you-have-tax-id-in-japan/

* Examples:
  * 7000012050002

**Comment by unho** [comment]
@arthurdejong Shouldn't this issue be closed now that https://github.com/arthurdejong/python-stdnum/commit/37e603204b0a43bc1debb421ffd2da280be4343c has been merged?

**Comment by unho** [comment]
@arthurdejong By the way, will be there any release soon? Thanks in advance.

**Comment by arthurdejong** [comment]
@unho Thanks, closing.

**Comment by arthurdejong** [comment]
Hi @unho python-stdnum 1.12 has just been released.
