### ISSUE TITLE
Cant import DO module, no module named.

### ISSUE THREAD

**Issue by ljacobo** [arthurdejong/python-stdnum#155]
Hi,

im trying to use the DO module to validate info of dominican republic but python doesn't recognize the DO module.

>>> import stdnum.do
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named do

i am using python2.7.

thnks

**Comment by arthurdejong** [comment]
How did you install python-stdnum?

**Comment by arthurdejong** [comment]
Closing because of lack of response. If this is still an issue feel free to re-open or create a new issue.
