### ISSUE TITLE
isin.py#L76 is missing some "special" "country" codes: 'XF', 'QS', 'QT', 'QW'

### ISSUE THREAD

**Issue by alexbond73** [arthurdejong/python-stdnum#158]
https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/isin.py#L76 is missing some "special" "country" codes:
'XF', 'QS', 'QT', 'QW'

https://memim.com/international-securities-identification-number.html 
https://de.wikipedia.org/wiki/Internationale_Wertpapierkennnummer#Interne%20und%20sonstige%20ISINs
'For papers that are not publicly traded, banks can define internal ISINs for purposes of illustration in their IT systems. These begin with the pseudo - country code " XF " and not in the interbank transport (incl. Clearer, exchanges, etc. ) are used. The associated SIN begins with a zero, so that follow after the ISIN ticker symbol " XF " four zeros. Since they are only used internally, they are not unique, ie, different banks may have the same XF ISIN use for different securities. For example, the ISIN was awarded XF0000C14922 for repair claims on Contitech shares until July 2012.

Since June 30, 2003 awards € Euroclear France interim dummy ISIN according to ISO 6170, starting with " QS".

In Switzerland ISIN codes are for securities, but do not have a regular ISIN Security number, assigned, starting with QT. Next comes the Swiss security number and then the ISIN check digit.

Deleted WKN, ISIN who have not yet obtained an ISIN with the prefix " QW ".'

**Comment by arthurdejong** [comment]
Hi Alex,

Thanks for pointing this out and sorry for taking so long to respond. This should be fixed in 87c195f.
