### ISSUE TITLE
GS1 format

### ISSUE THREAD

**Issue by thiagola92** [arthurdejong/python-stdnum#175]
The same calculation from GTIN (EAN/UCC) format is used to GLN, SSCC, GSRN, GSIN and GCN .  
https://www.gs1.org/services/how-calculate-check-digit-manually  
https://www.gs1.org/docs/barcodes/GS1_General_Specifications.pdf (page 22)  
https://www.gs1.org/services/check-digit-calculator  

Is possible to create one module for all formats. What you think?

**Comment by arthurdejong** [comment]
Hi @thiagola92,

The GTIN codes are already supported in the `stdnum.ean` module. Recently a `stdnum.gs1_128` module was also added that can be used to validate and build GS1-128 barcode values.

I think that mostly leaves GSIN and SSCC which are currently not yet implemented.

**Comment by thiagola92** [comment]
I belive this can be close, because GSIN and SSCC in:  
https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/gs1_ai.dat
