### ISSUE TITLE
Italian fiscal code ("codice fiscale") should accept VATs

### ISSUE THREAD

**Issue by LordGordonQ** [arthurdejong/python-stdnum#180]
The current validation of an Italian fiscal code ("codice fiscale", https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/it/codicefiscale.py) is incomplete, since by definition an Italian fiscal code could be:
 - for individuals is 16 characters long (current implementation)
 - for non-individuals (institutions, organizations, ...) is 11 characters long with the same rules for Italian VAT (https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/it/iva.py)

Reference: https://it.wikipedia.org/wiki/Codice_fiscale (italian). I'm unable to find a proper english translation. Event the english Wikipedia seems incomplete. 
 
Notice: the opposite is not true. An Italian VAT cannot be 16 characters long.

**Comment by arthurdejong** [comment]
Hi Nicholas,

Thanks for pointing this out. Does the individual number also have a distinctive name that can be used to reference it? If so it may be a good idea to add a separate module for that and have codicefiscale just reference the two modules, otherwise I'll add checking for the VAT to the codicefiscale module.

**Comment by LordGordonQ** [comment]
@arthurdejong 

Hi Arthur, the the individual number is called "Codice Fiscale", while the non-individual number is the "Partita IVA" (VAT).  So, basically:

- a "Partita IVA" is always an 11 character length code, for business entities (and similar). Current implementation of Partita IVA is correct.
- a "Codice Fiscale" is the proper name of the code for individual entities and it is 16 character longs. Yet, non-individuals have the "Codice Fiscale" being equal to their own "Partita IVA", thus having a "Codice Fiscale" of 11 characters.

There are not other names (to my knowledge). I hope I have clarified it (I know, little messy).

So, yes, if you have a Codice Fiscale of 11 characters, it should not be refused and it should be validated against the partitaiva (vat) module instead. In fact in my original post I missed to provide some expected behaviour for codicefiscale module:

- `validate('RCCMNL83S18D969H')` accepted as it is a valid individual Codice Fiscale
- `validate('RCCMNL83S18D969')` not accepted (wrong length)
- `validate('00743110158')` accepted as it is a Codice Fiscale for non-individual (using partitaiva validation)
- `validate('00743110158')` not accepted as it is not a valid Partita IVA, so it cannot be a Codice Fiscale for non-individuals.
- `validate('IT00743110158')`? I expect to be valid because I'm writing the "Partita IVA" in the VATIN format (EU), with the country code. I think this is up to the implementation to accept or refuse this case, as the law says nothing to my knowledge.

**Comment by arthurdejong** [comment]
Thanks for the clarification. I've fixed it in 9605dbe.

For now I've not allowed the IT prefix in the Codice Fiscale until it becomes common within Italy to use the prefix in the Codice Fiscale.
