### ISSUE TITLE
Issue with some Italian VAT codes (Partita IVA)

### ISSUE THREAD

**Issue by LucaCappelletti94** [arthurdejong/python-stdnum#206]
Hello Arthur and first of all thank you for making this wonderful library!

I wanted to report you a few errors I encountered with the Italian VAT codes.

The following VAT codes fail:
- [01256588755](http://trasparenza.polimi.it/ugov/trasparenza/328972)
- [02031760410](https://apps.unive.it/trasparenza/2016/115)

But they are indeed valid as you can see from the sources.

I am very ignorant in the matter of VAT codes validation, I just wanted to let you know. For my own script, I'll simplify the validation to be a list of 11 numbers after an optional "IT".

Good luck!

**Comment by arthurdejong** [comment]
Hi @LucaCappelletti94 thanks for your report.
Both numbers also fail the online [VIES validation by the European Commision](http://ec.europa.eu/taxation_customs/vies/) so I would assume that they are errors on the respective pages rather than a bug in `pythion-stdnum`.
