### ISSUE TITLE
cant import stdnum.ve

### ISSUE THREAD

**Issue by festovalros** [arthurdejong/python-stdnum#216]
hi! i try to import stdnum.ve but not module named stdnum.ve error occurs, this only happen with python 3, i tested the same import with python 2.7 and no error ocurrs.

i installed the last version of stdnum (1.13 to the date) with pip in both cases.

**Comment by arthurdejong** [comment]
Can you show me how you installed python-stdnum and what error you get when trying to `import stdnum.ve`?

**Comment by festovalros** [comment]
hi! i updated python-stdnum to the last version available (1.13) and it's working now, thanks for the feedback
