### ISSUE TITLE
Add validation for Vietnam TIN

### ISSUE THREAD

**Issue by unho** [arthurdejong/python-stdnum#217]
* It is called "Mã số thuế" (translated as "Tax Code") or "MST" (short version) and it is 10 digits long. 
  * Also called "Mã số người nộp thuế" (translated as "Taxpayer Identification Number") according to image of some official certificate in https://easyinvoice.vn/ma-so-thue/ but Google tells that the above one is much much commonplace.
* https://vi.wikipedia.org/wiki/Thu%E1%BA%BF_Vi%E1%BB%87t_Nam#M%C3%A3_s%E1%BB%91_thu%E1%BA%BF_(MST)_c%E1%BB%A7a_doanh_nghi%E1%BB%87p includes description and details about structure.
* https://easyinvoice.vn/ma-so-thue/
* https://ub.com.vn/threads/huong-dan-tra-cuu-ma-so-thue-doanh-nghiep-moi-nhat.261393/
* https://vietluat.vn/nhung-dieu-can-biet-ve-ma-so-thue-ma-so-doanh-nghiep.html
* https://dhlaw.com.vn/ma-so-thue-la-gi-y-nghia-ma-so-thue/

Online search:
* http://tracuunnt.gdt.gov.vn/tcnnt/mstdn.jsp
* https://masothue.vn/

Implementations:
* Excel formula https://www.giaiphapexcel.com/diendan/threads/c%C3%B3-c%C3%A1ch-n%C3%A0o-ki%E1%BB%83m-tra-m%C3%A3-s%E1%BB%91-thu%E1%BA%BF-c%C3%B3-ph%C3%B9-h%E1%BB%A3p-tr%C6%B0%E1%BB%9Bc-khi-l%C3%AAn-h%C3%B3a-%C4%91%C6%A1n-kh%C3%B4ng.22792/#post-158100
* https://www.giaiphapexcel.com/diendan/threads/ki%E1%BB%83m-tra-m%C3%A3-s%E1%BB%91-thu%E1%BA%BF-h%E1%BB%A3p-l%E1%BB%87-b%E1%BA%B1ng-excel.3537/#post-24446
* https://www.giaiphapexcel.com/diendan/threads/ki%E1%BB%83m-tra-m%C3%A3-s%E1%BB%91-thu%E1%BA%BF-h%E1%BB%A3p-l%E1%BB%87-b%E1%BA%B1ng-excel.3537/#post-155906
* https://www.giaiphapexcel.com/diendan/threads/ki%E1%BB%83m-tra-m%C3%A3-s%E1%BB%91-thu%E1%BA%BF-h%E1%BB%A3p-l%E1%BB%87-b%E1%BA%B1ng-excel.3537/#post-154873
* (download link is broken, but I asked the author and he kindly shared the code) https://tinhte.vn/thread/133546#post-1184823
  * The shared code [ChkCont.cpp.zip](https://github.com/arthurdejong/python-stdnum/files/4576192/ChkCont.cpp.zip)

Examples:
* 0105958840 from https://masothue.vn/0105958840-cong-ty-co-phan-giai-phap-cong-nghe-wiki
* https://masothue.vn/
  > 3300273243-005
4900813164
5800199577-002
5900705097
0314179100
5500340437
0201909807
0201910834
5200869050
0314409058-002
1300440846-008
3301595028
1600699712-004
3100104093-009
2000730546-015
2000961769-009
5200327611
0103131621
4401031161
5400478872
0102641429-066
3702499152
4001100318
1600255033-006
4900224296
3400416992-007
0700790272
* Found on the Internet
  > 0100112437011
0101245486
0102182292
0102723382
0105330703
0105958840
0106142205
0106713191
0106824279
0107338930
0107371744
0107430703
0107526719
0107959889
0107984081
0108024302
0108256430
0108747679
0108880215
0109120150
0109161862
0300533351
0302082048
0303104343
0304475742
0304541339
0305000124
0305060028
0305322160
0306404183
0308023320
0309485335
0311592398
0311693854
0311892472
0311933841
0312386285
0312615305
0312971744
0313322647
0313511637
0313844499
0313883096
0314390745
0314425155
0314715626
0314797650
0314817730
0315469356
0315641254
0315649013
0315675711
0316095304
0316110224
0400129230
0401 443 048
0401958914
1601223524
1801314923
2500291713
2901807716
3200707377
3602404615
3603718156
3700635642
3700751416
3702642596
3900956516
4000107409
4001170925
4200919944
4201783848
8037630690
8463763902
2000102580
2000102580-001
2000102580-002
2000102580-003
2000102580-004
2000102580-005
2000102580-006
2000102580-007
2000102580-008
2000102580-009
2000102580-010
2000102580-011
2000102580-012
2000102580-013
2000102580-014

**Comment by arthurdejong** [comment]
Thanks! Merged as a34a76d.
