### ISSUE TITLE
Add support for Morocco TIN

### ISSUE THREAD

**Issue by unho** [arthurdejong/python-stdnum#226]
* http://world.salestaxhandbook.com/ma-morocco
* It looks like there are several numbers:
  * Identifiant Fiscal (IF) (maybe also called "n° d’identification fiscale"? Also called `Identification Fiscale`. `التعريف الضريبي` in Arabic)
  * numéro de registre de commerce (RC), `رقم السجل التجاري` in Arabic.
  * numéro de CNSS (CNSS), `رقم القيد في الصندوق الوطني للضمان الإجتماعي` in Arabic. This is the Social Security number.
  * Identifiant Commun de l’Entreprise (or ICE for short, `التعريف الموحد للمقاولة` in Arabic)
    * http://www.ompic.org.ma/fr/content/identifiant-commun-de-lentreprise
    * https://www.ice.gov.ma/ICE/Depliant_ICE.pdf
    * https://www.ice.gov.ma/ICE/Guide_ICE.pdf
    * https://www.ice.gov.ma/ICE/
    > L’ICE est un identifiant composé de 15 positions :
  • l’entreprise (9 positions) ;
  • ses établissements (4 positions) ;
  • des caractères de contrôle (2 positions). 
* According to https://www.upsilon-consulting.com/2022/01/identifiant-fiscal-au-maroc/ it looks like the IF only identifies you to the tax authorities, while the ICE works for all Morocco government branches, so perhaps the ICE is preferable.

Search:
* https://www.ice.gov.ma/ICE/login.xhtml

Examples (ICE):
* `001561191000066` from https://www.boursenews.ma/uploads/communiques/630e1c17159a4_CP%20LHM%20T2%202022.pdf which also lists the other codes.
* `001527456000081` from https://www.wafasalaf.ma/fr
* `002163624000014` from https://sport7.ma/
* `000039557000028` from https://www.lemonopole.ma/annonce/annonce-legale-sadri-travel/
* `000030205000041` from https://www.albaridbank.ma/ar/asharat-qanwnyt
* `002968168000088` from https://www.damascene.ma/
* `1781980000092` and `36794000036` (with enough leading zeroes, they work) from https://www.alomrane.gov.ma/content/download/36852/file/Liste%20des%20entreprises%20exclues%20%C3%A0%20la%20participation%20aux%20march%C3%A9s%20du%20GAO%20-%20Copie.pdf
* A lot of examples on https://startuphub.ma/index.php?page=portail.ListeJEI&portail=tfc4puliqv2hpl9pe7tm0bon2v
  * 001996344000060
  * 002073147000045
  * 002009081000026
  * 001731355000043
  * 002140237000090
  * 001841032000077
  * 001691344000051
  * 000306730000053
  * 001827913000046
  * 002034945000001
  * 000121494000008
  * 001697352000019
  * 002247135000079
  * 001899950000091
  * 001761860000035
  * 002139783000029
  * 002223396000056
  * 002169811000096
  * 002046464000067
  * 001969336000030
  * 001719647000036
  * 002295895000043
  * 001680801000017
  * 001798692000015
  * 001966274000060
  * 001747979000014
  * 002323180000063
  * 001906225000028
  * 002063738000045
  * 002301187000040
  * 002079718000041
  * 001976463000049
  * 002187910000012
  * 001972954000023
  * 001883389000068
  * 002153925000084
  * 001962219000032
  * 001911196000059
  * 001951042000044
  * 000340280000086
  * 001565457000023
  * 001521348000097
  * 002020847000019
  * 001867807000093
  * 002058647000053
  * 000136283000054
  * 001587995000075
  * 001744856000042
  * 002200638000027
  * 002175561000046
  * 002018167000017
  * 002270907000084
  * 001974718000022
  * 001984827000037
  * 002281761000063
  * 000112460000068
  * 002037826000008
  * 000307651000018
  * 002333592000045
  * 001748885000093
  * 001757319000034
  * 002318242000014
  * 002216313000013
  * 002296176000022
  * 001604356000066
  * 000514866000076
  * 002352204000078
  * 001920114000027
  * 002038222000083
  * 001971196000056
  * 002196660000054
  * 002362254000037
  * 001779428000029
  * 002356643000020
  * 002350352000030
  * 002044907000008
  * 001629924000079
  * 002239990000061
  * 002395685000082
  * 002051971000079
  * 002276099000065
  * 002127913000031
  * 001566453000097
  * 002332839000006
  * 002032229000001
  * 002143987000011
  * 002117772000007
  * 001806095000051
  * 001918345000066
  * 002033432000015
  * 001596169000052
  * 002316584000063
  * 002062968000077
  * 002090034000093
  * 001803717000043
  * 002233325000081
  * 001940537000051
  * 002329576000031
  * 002231202000075
  * 002171831000070
  * 002411565000062
  * 002412224000020
  * 001992467000076
  * 001753989000025
  * 002296470000038
  * 002330015000012
  * 002398966000056
  * 002397991000094
  * 002393076000006
  * 001728812000028
  * 002272559000003
  * 001849085000023
  * 002398706000092
  * 001989898000084
  * 002335910000024
  * 002446492000067
  * 002434341000090
  * 002057377000005
  * 002284350000097
  * 002105112000096
  * 002228150000029
  * 002252304000002
  * 002304491000072
  * 002315467000055
  * 002568544000044
  * 002332952000059
  * 002579366000014
  * 002161178000096
  * 002417172000090
  * 002538729000046
  * 002085583000087
  * 001680240000032
  * 002014761000023
  * 001981508000022
  * 001977144000092
  * 002056833000046
  * 002428800000026
  * 002289496000059
  * 001887940000090
  * 002381289000095
  * 002533410000002
  * 002405881000076
  * 001849141000063
  * 002253380000050
  * 002553650000020
  * 002435009000096
  * 002387721000061
  * 002621267000095
  * 001985336000068
  * 002630734000081
  * 001981648000025
  * 002552275000091
  * 002371582000090
  * 002316916000023
  * 002211141000074
  * 002484695000084
  * 002661194000027
  * 001965640000009
  * 001665196000081
  * 001635704000092
  * 002328845000077
  * 002516759000081
  * 002014024000037
  * 002673962000029
  * 002096915000061
  * 002676213000071
  * 002586051000036
  * 002640613000001
  * 002557636000068
  * 002006117000029
  * 002140808000096
  * 002563030000027
  * 002567289000076
  * 002554671000001
  * 002146682000093
  * 002680896000021
  * 002591358000016
  * 001941895000051
  * 002171053000027
  * 002700176000060
  * 002076600000031
  * 002672505000083
  * 002612930000057
  * 002539687000079
  * 002443493000045
  * 002512492000054
  * 002017829000025
  * 001966328000057
  * 002591278000042
  * 002410367000010
  * 002137019000064
  * 002131581000032
  * 002732141000014
  * 002702346000058
  * 002727761000031
  * 002134880000005
  * 002623148000039
  * 002375962000073
  * 002672209000024
  * 001977973000019
  * 002143491000017
  * 000208893000051
  * 002437842000041
  * 002548326000014
  * 002364621000051
  * 002531222000005
  * 002311049000031
  * 002550790000028
  * 002214705000070
  * 002397938000070
  * 002738846000078
  * 002701712000007
  * 002755277000022
  * 002162611000011
  * 002023306000071
  * 002430830000021
  * 002158476000009
  * 002183254000012
  * 002411901000011
  * 002753855000004
  * 002695875000078
  * 002855545000056
  * 002779500000072
  * 002758755000012
  * 002735223000026
  * 002876027000039
  * 002129534000011
  * 002710658000092
  * 002604451000070
  * 002900436000014
  * 002558898000041
  * 001938437000006
  * 002848452000089
  * 002623198000047
  * 002896112000071
  * 002150724000084
  * 002234477000017
  * 002524051000010
  * 002023181000051
  * 001582022000035
  * 002356463000030
  * 002460994000005
  * 002365137000087
  * 002706140000052
  * 002614910000044
  * 002778012000090
  * 002789171000079
  * 002007999000043
  * 002627640000005
  * 002229460000064
  * 002548398000010
  * 002394801000088
  * 002890804000021
  * 002404272000063
  * 002762731000039
  * 002955648000083
  * 002603912000073
  * 002396429000073
  * 002029820000054
  * 002941675000024
  * 002581462000070
  * 002731533000037
  * 002963798000029
  * 002101840000073
  * 002944298000013
  * 002544785000076
  * 002290426000072
  * 002186697000074
  * 002535481000054
  * 002883860000008
  * 002029059000037
  * 002378437000081
  * 002563399000055
  * 002534287000088
  * 002792346000005
  * 002789456000047
  * 001655795000059
  * 002064672000047
  * 002413919000039
  * 002926185000087
  * 002759985000073
  * 002904997000057
  * 002667689000038
  * 002583852000045
  * 002158470000074
  * 002080593000084
  * 002637104000072
  * 002947862000009
  * 002497670000026
  * 002738572000007
  * 002814353000038
  * 002686362000073
  * 002564248000024
  * 002336083000009
  * 003033702000047
  * 002953812000088
  * 003015196000062
  * 002055912000081
  * 002828094000056
  * 003065707000085
  * 002937556000075
  * 002644007000028
  * 001977166000080
  * 003102867000036
  * 003102159000043
  * 002209982000036
  * 002143108000076
* `000206981000071` from https://technoplace.ma/content/7-mentions-legales
* `002838477000045` from https://www.savey.ma/fr/conditions-generales-dutilisation
* `003004995000009` from https://trainet.ma/Orga/Organisation/Details?ID=161
* `000106304000022` from https://monordi.ma/propos/
* `002891370000065` from https://pcboost.ma/
* `00 21 36 09 30 00 040` from https://iav.ac.ma/fr/cooperation-nationale
* `000303003000093` from https://www.yapo.ma/
* `000084803000004` from https://www.feniebrossette.ma/wp-content/uploads/2019/02/RAPPORT-FINANCIER-ANNUEL-RAPPORT-ESG-2020-1.pdf
* `001512572000078` from https://www.bankofafrica.ma/fr/campagne-dactivation-cartes-visa-reglement-de-tombola
* `001544732000005` from http://www.carre.ma/resaux-agences.php
* `001713071000078` from https://www.energiedin.ma/
* `001580232000059` from https://www.radeec.ma/gralteku/2021/08/RADEEC-Avis-de-recrutement-6-Ouvriers-05.pdf

**Comment by unho** [comment]
It looks like there is a mess of numbers. I am leaving this for later.

**Comment by arthurdejong** [comment]
The check digit algorithm seems to be based on ISO 7064 Mod 97,10 but normally the checksum value for valid numbers is expected to be 1 while in this case all the provided test numbers have a checksum value of 0.
