### ISSUE TITLE
Support new Austrian postal code list

### ISSUE THREAD

**Issue by arthurdejong** [arthurdejong/python-stdnum#235]
The current update script (`update/at_postleitzahl.py`) fails because the page it used (https://www.post.at/en/business_advertise_products_and_services_addresses_postcodes.php) no longer exists, probably because the postal service changed their website.

Currently there is https://www.post.at/sf/standortfinder which offers search functionality. There is also https://api.www.post.at/ which does not have clear documentation but [this URL](https://api.www.post.at/postat/xp/public/DepositoryService/GetDepositoriesForWeb?lang=de-AT&distance=1000000&latitudeWGS84=47.5828798&longitudeWGS84=12.6915545&type=2) at least seems to return all post offices (unsure if that includes all postal codes through). It returns 2168 post offices while the previous list 2221 postal codes. There could also be another API endpoint that includes more useful information.

Any help here would be welcome, especially if someone knows a little more about the Austrian postal system.

**Comment by brot** [comment]
There is on Austrian open-data portal on which you can find and use the [list of postal-codes](https://www.data.gv.at/katalog/dataset/f76ed887-00d6-450f-a158-9f8b1cbbeebf). The data is available as CSV, XML or JSON

**Comment by arthurdejong** [comment]
Thanks @brot 

In a0c62ee the update script was changed to use a spreadsheet downloaded from https://www.post.at/g/c/postlexikon instead but this is indeed much better (fixed in 407a02f).

I did filter the list to only include those that have "adressierbar" as "Ja" because that matches the old list.
