### ISSUE TITLE
{possible bug} /ar/dny.py missing on Debian

### ISSUE THREAD

**Issue by gabrieled07** [arthurdejong/python-stdnum#249]
Hi, I would like to report you a possible bug in the packages distributed with Debian 10.

trying to install Tryton, got to the point where an exception was triggered.
<code>
ModuleNotFoundError: No module named 'stdnum.ar.dni'
</code>

and, in fact dny.py was not present on the pip3 installed packages (/usr/local/lib/python3.7/dist-packages/python_stdnum.../stdnum/ar), just cuit.py and cbu.py

installing your package from this github however, solve the problem.

It might be a mismatch version, a recent change that was not yet replicated, or something specific with the way I'm doing things.
Not a software developer, just a sysadmin. 
I wanted to spend a little time to report this as I had to investigated and found the culprit.

Than you, 
Regards,
Gabriel

**Comment by arthurdejong** [comment]
Hi Gabriel,

The Argentinian DNI was added in [release 1.11 of python-stdnum](https://arthurdejong.org/python-stdnum/doc/changes#changes-from-1-10-to-1-11) and Debian buster (10) has release 1.10 of python-stdnum. If you install a recent version of python-stdnum via pip it should also be available.

Debian has a policy against uploading new features to stable releases (unless there are very pressing reasons) so this is unlikely to be fixed within Debian stable. If you can reproduce this error with the version of Tryton that is shipped within Debian 10 it is a good idea to create a but report there (see [these instructions on how to report a bug in Debian](https://www.debian.org/Bugs/Reporting)). What could be done is creating a newer release of python-stdnum in the [Debian backports archive](https://backports.debian.org/) but for most use cases installing the package yourself with pip (possibly in a virtualenv) is likely your best bet.

Hope this helps.
