### ISSUE TITLE
Brexit - New VAT numbers for companies in Northern Ireland starting with XI

### ISSUE THREAD

**Issue by alexis-via** [arthurdejong/python-stdnum#250]
Following Brexit on January 1st 2021, companies in Northern Ireland have a new VAT number starting with XI, that should be used for transaction of goods between EU and Northern Ireland (because these transactions are still under EU VAT regime !). More info here: https://www.gov.uk/government/publications/accounting-for-vat-on-goods-moving-between-great-britain-and-northern-ireland-from-1-january-2021/check-when-you-are-trading-under-the-northern-ireland-protocol-if-you-are-vat-registered-business
As far as I understand, this new VAT number is just the old VAT number where "GB" has been replaced by "XI".

I tested with stdnum v1.15 and VAT numbers starting with XI are considered invalid. I tested with the VAT number below that is stated as valid by VIES (the online service of the EU commission for VAT numbers):

![vat_xi_vies](https://user-images.githubusercontent.com/1157917/105388141-95f79a00-5c16-11eb-8350-ddf770e71291.png)

**Comment by arthurdejong** [comment]
Thanks for providing the sample number and link, that really helps. I was unsure what the format of the numbers was exactly because none of the numbers I could find were valid according to VIES (#246).

**Comment by alexis-via** [comment]
Thank you very much for this super-fast update! It works well via stdnum.gb.vat, but not via stdnum.vatin ; my PR above fixes it.
