### ISSUE TITLE
Flip values greece "gr" to "el" at VIES validation

### ISSUE THREAD

**Issue by bapons** [arthurdejong/python-stdnum#256]
# Flip greek codes "gr" -> "el"

As we know VIES greek code accepted is **EL** 
For that would be nice to flip values if we detect the code is **GR** before making the request to VIES wsdl. 

The library already does something similar to get the module from the country of Greece but on the contrary.

[Related code](https://github.com/arthurdejong/python-stdnum/blob/075d85e8e45b7deda49c034949e9a71288150a41/stdnum/eu/vat.py#L61)
```python
def _get_cc_module(cc):
    """Get the VAT number module based on the country code."""
    # Greece uses a "wrong" country code
    cc = cc.lower()
    if cc == 'el':
        cc = 'gr'
    if cc not in MEMBER_STATES:
        return
    if cc == 'xi':
        cc = 'gb'
    if cc not in _country_modules:
        _country_modules[cc] = get_cc_module(cc, 'vat')
    return _country_modules[cc]
```

I was thinking of something like this
[Related code](https://github.com/arthurdejong/python-stdnum/blob/075d85e8e45b7deda49c034949e9a71288150a41/stdnum/eu/vat.py#L123)

```python
def check_vies(number, timeout=30):  # pragma: no cover (not part of normal test suite)
    """Query the online European Commission VAT Information Exchange System
    (VIES) for validity of the provided number. Note that the service has
    usage limitations (see the VIES website for details). The timeout is in
    seconds. This returns a dict-like object."""
    # this function isn't automatically tested because it would require
    # network access for the tests and unnecessarily load the VIES website
    number = compact(number)
    if number[:2] == "GR":
        number = f"EL{number[2:]}"
    client = get_soap_client(vies_wsdl, timeout)
    return client.checkVat(number[:2], number[2:])
```

**Comment by arthurdejong** [comment]
I don't think that for example `GR039868210` is a valid Greek VAT number while the same number starting with `EL` is considered valid. If a VAT number starting with GR is documented to be valid in some cases we should probably modify the `compact()` function to replace `GR` with `EL`

**Comment by bapons** [comment]
Totally true about `GR03986821`, is not a valid VAT number. 
I just thought could be a good idea to change values before call VIES service, just for Greece. Because it is an exception compared with the other countries.
