### ISSUE TITLE
Replace suds with a python 3 compatible SOAP library

### ISSUE THREAD

**Issue by sebest** [arthurdejong/python-stdnum#26]
Hello,

Would it be possible to replace suds by a python 3 compatible SOAP library like: https://github.com/pysimplesoap/pysimplesoap

thanx

**Comment by arthurdejong** [comment]
That would probably be a good idea. I've also had a look at spyne which seems mostly focussed on server-side applications and a few more (soaplib, soappy and zsi) which seem to be old, deprecated or unmaintained.

I've had a quick look at pysimplesoap and the API looks simple enough. Proxy support does not seem very good though (only supporting SOCKS from the looks of it).

Implemented in a1a134e91b0ca3ccdff69929c4555c62e10c8714.
