### ISSUE TITLE
No validation found for Belgium card No

### ISSUE THREAD

**Issue by amatmv** [arthurdejong/python-stdnum#282]
Morning, 

I am figuring how to validate a Belgium card No. The document described in https://en.wikipedia.org/wiki/Belgian_identity_card

For belgium I am only finding documents iban and the Belgian enterprise number. But there is the personal card No, that has 12 digits.

Maybe a PR is needed?

**Comment by arthurdejong** [comment]
There are two numbers mentioned on that page:

- *Rijksregisternummer* (aka "identificatienummer van het Rijksregister" and previously "nationaal nummer") which consists of 11 digits and is a mostly permanent number assigned to individuals. [1](https://nl.wikipedia.org/wiki/Rijksregisternummer) [2](https://www.ibz.rrn.fgov.be/nl/rijksregister/faq/meer-technische-informatie-it-autogeneratie-wijzigingen/) (related to that is the bisnummer and both are valid INSZ numbers [3](https://overheid.vlaanderen.be/insz-nummer))
- *The card number* (identiteitskaartnummer) this number is unique to the card and seems to be either 12, 9 or 10 (a letter and 9 numbers) digits. This number seems to be similar to passport numbers which, in many countries, are not unique identifiers for persons. There seems to be very little information on this card number available.

**Comment by cedk** [comment]
For this has been implemented in #284
