### ISSUE TITLE
BUG on validate RUC for Ecuador (EC)

### ISSUE THREAD

**Issue by francisrubio06** [arthurdejong/python-stdnum#290]
The _is_valid_ method returns false with two RUCs already registered in the government.

**RUC: 0993370026001**

![image](https://user-images.githubusercontent.com/19362305/156791504-37132a92-19b1-4c6c-9a7d-6bfc0f9ab6fe.png)

![image](https://user-images.githubusercontent.com/19362305/156792274-7e3a141e-d7a6-41b6-8411-d13a0b375994.png)

**RUC: 1793189624001**

![image](https://user-images.githubusercontent.com/19362305/156791605-bfeb35b2-4387-47af-a252-0f6436ef0ce7.png)

![image](https://user-images.githubusercontent.com/19362305/156792655-4f805df4-232d-4098-95a5-043009e09027.png)

**Comment by arthurdejong** [comment]
Thanks for reporting this. If you know a reliable source describing the format and validation I'd be more than happy to adapt the code. As it stands now it is mostly built up using bits and pieces that were provided by various people.

The current module first determines if the RUC is a natural, public or juridical number (based on the third digit) and then does the validation based on that. Both 0993370026001 and 1793189624001 are classified as juridical numbers (third digit is a 9) and the corresponding check digit validation fails. The 1793189624001 number validates as public RUC but 0993370026001 does not.

Without more documentation this is sadly very hard to fix properly.
