### ISSUE TITLE
BUG on validate SIRET code

### ISSUE THREAD

**Issue by BIGBen99** [arthurdejong/python-stdnum#291]
Python-stdnum rejects valid SIRET code (356 000 000 09075). Some SIRET codes are valid instead of validating Luhn algorithm.

For SIRET code that don't validate Luhn algorithm, the sum of all digits should be a multiple of 5.
https://www.sirene.fr/sirene/public/recherche
![Annotation 2022-03-07 121436](https://user-images.githubusercontent.com/11870973/157028384-613a5c6b-2331-4307-9c77-709c05ce2a7e.png)

**Comment by cedk** [comment]
Indeed it is only the SIRET of "La Poste" that [has an exception](https://fr.wikipedia.org/wiki/Syst%C3%A8me_d%27identification_du_r%C3%A9pertoire_des_%C3%A9tablissements#Exceptions_pour_le_groupe_La_Poste).

**Comment by arthurdejong** [comment]
Thanks @BIGBen99 for reporting this. Thanks @cedk for looking into this and providing the fix. It has been merged as 73f5e3a.

**Comment by alexis-via** [comment]
Thanks! I hope we'll have a new release on pypi soon so that all users can benefit from this fix.

**Comment by alexis-via** [comment]
@arthurdejong Would it be possible to make a new release of stdnum, so that non-expert users can benefit from this fix (and certainly others) ?

**Comment by arthurdejong** [comment]
Hi @alexis-via,
Sorry it took so long but release 1.18 was just uploaded to PyPI that includes this fix (and more).
