### ISSUE TITLE
Add Kenya TIN number

### ISSUE THREAD

**Issue by unho** [arthurdejong/python-stdnum#300]
It is called PIN (Personal Identification Number) and is issued by the KRA (Kenya Revenue Authority).

* https://www.kra.go.ke/individual/individual-pin-registration/learn-about-pin/about-pin
* https://org-id.guide/list/KE-KRA
* https://www.cyber.co.ke/how-to-get-kra-pin-number-certificate-using-kra-portal/
  * According to this it is 11 digits long.
* https://stackoverflow.com/questions/51556967/how-to-preg-match-kra-pin-no
* https://docs.appruve.co/appruve-identity/kenya/verify-kenya-kra-pin
* https://api-docs.dojah.io/docs/lookup-kenya-tin
* https://www.facebook.com/KRACare/posts/personal-identification-number-pin-is-a-number-which-identifies-a-person-for-pur/1110866462257692/
* https://m.facebook.com/KRACare/photos/tip-of-the-day-httpsitaxkragoke/1270332812977722/

Online checker:
https://itax.kra.go.ke/KRA-Portal/pinChecker.htm

Validation code:
* https://gist.github.com/NimzyMaina/c32e6dc0ca9d6b83c6d28e3e25065677

Examples:
* A004416331M
* P051365947M
* P000594434U
* https://dennykinsassociates.com/kra-pin-numbers-for-all-companies-in-kenya/
  * P000619379O
  * P000609147B
  * P000595101M
  * P000594873H
  * P000608609Y
  * P000605255W
  * P000591260N
  * P000591376W
  * P051126254X
  * P000609718Z
  * P000594487J
  * P000599642I
  * P000615147U
  * P000619594P
  * P000608167F
  * P000609671I
  * P000597382L
  * P000598207Z
  * P000596967Q
  * P051099534I
  * P051116151S
  * P000597694S
  * P000597676Q
  * P000591115C
  * P000597819E
  * P051117306P
  * P000615058Y
  * P000608932A
  * P051124533N
  * P051123493Y
  * P051106014G
  * P051102575T
  * P051159129C
  * P051094112J
  * P000592089D
  * P000591575X
  * P000605619R
  * P051120393R
  * P000611519E
  * P051141902D
  * P000604053O
  * P000595728D
  * P051097904C
  * P000592118K
  * P051110833H
  * P000598418B
  * P051132776Z
  * P000592851X
  * P051127959L
  * P000602904I
  * P000598609F
  * P000603130E
  * P051092962C
  * P051100289S
  * P000595362D
  * P000607298L
  * P000592366Z
  * P000593471Z
  * P000593248W
  * P000596998X
  * P000637719Z
  * P000603639S
  * P000598522B
  * P000598224A
  * P000610622O
  * P051098974U
  * P051100248H
  * P051194673F
  * P000592265X
  * P051102426H
  * P000593809V
  * P051151506E
  * P000596373I
  * P051160236J
  * P000602920I
  * P000607322Q
  * P051094227U
  * P000595438C
  * P000607839E
  * P051130656Q
  * P051104242J
  * P051093274B
  * P000597143A
  * P000613824O
  * P000595467J
  * P051147495M
  * P000595273F
  * P051139006S
  * P000605674D
  * P000615432Q
  * P000606270X
  * P000600314X
  * P000595037X
  * P000618428A
  * P000594433T
  * P000598330Z
  * P000599567S
  * P000595108T
  * P051127968M
  * P051153177Y
  * P051170839T
  * P051155350V
  * P051133887F
  * P000591465U
  * P000591400B
  * P000619647H
  * P000609354E
  * P000609363F
  * P000609346C
  * P000593916S
  * P051153543Q
  * P000611951N
  * P000609364G
  * P051099723H
  * P000609367J
  * P000612260M
  * P000609358I
  * P000609355F
  * P000612829R
  * P000609340W
  * P000609370E
  * P051124237Z
  * P000609342Y
  * P000609351B
  * P000609360C
  * P000609361D
  * P000612067R
  * P000609362E
  * P000609344A
  * P051092778I
  * P051099651M
  * P051149832D
  * P000609341X
  * P051141061H
  * P000609237A
  * P000609348E
  * P051097559P
  * P000633040I
  * P000609345B
  * P000609356G
  * P000609357H
  * P051112430E
  * P000609359J
  * P000609365H
  * P000597328D
  * P000629820Z
* https://kicc.co.ke/wp-content/uploads/2021/03/List-of-Suppliers-2020-2021.pdf (dozens of them, listed under the "Pin certificate"  (in several tables), "KRA Pin" (in several tables), "Pin Number", "PIN No" (in several tables) columns)
* http://keib.or.ke/wp-content/uploads/2019/03/List-Of-Prequalified-Suppliers-For-Financial-Year-2018-2020-1.pdf (dozens of them)
* https://www.kcaa.or.ke/sites/default/files/tenders/awarded/LIST%20OF%20CONTRACT%20AWARDS%20%20FOR%20GOODS%2C%20WORKS%20AND%20SERVICE%20AWARDED%20IN%20THE%20MONTH%20OF%20FEBRUARY%202021%20%281%29.pdf
* https://infotradekenya.go.ke/media/Registered%20Horticultural%20Exporters%202020%20(1).pdf
* https://www.tum.ac.ke/noticeboard/dl?id=4upjv4uxx6rih
* https://kfcb.go.ke/sites/default/files/2021-10/List%20of%20Registered%20Suppliers%202020-2022.pdf
* https://www.yumpu.com/en/document/view/3301318/large-taxpayers-offic-kenya-revenue-authority

**Comment by arthurdejong** [comment]
There appears to be some kind of check digit algorithm used for calculating the last letter.

An increase in the last digit by one increases the check digit by one (with a wrap-around):

> P00060934**0W**
> P00060934**1X**
> P00060934**2Y**
> P00060934**4A**
> P00060934**5B**
> P00060934**6C**
> P00060934**8E**

I haven't found any examples to the contrary in the set of numbers provided.

However, the influence of the second to last digit is a bit more mysterious:

> P0006093**0**0**O**
> P0006093**2**0**S**
> P0006093**3**0**U**
> P0006093**4**0**W**
> P0006093**5**0**A**
> P0006093**6**0**C**
> P0006093**7**0**E**
> P0006093**8**0**G**
> P0006093**9**0**I**

It increases consistently by 2 characters, except in this case from 4 to 5 it goes from W to A instead of to Y. Another example:

> P0006096**0**1**S**
> P0006096**2**1**W**
> P0006096**3**1**Y**
> P0006096**4**1**A**
> P0006096**5**1**E**
> P0006096**6**1**G**
> P0006096**7**1**I**
> P0006096**8**1**K**
> P0006096**9**1**M**

Again the change from 4 to 5 goes from A to E instead of the expected C.

The third digit from the right seems to affect the check digit the same as the last digit:

> P051126**1**54**W**
> P051126**2**54**X**
> P051126**3**54**Y**
> P051126**4**54**Z**
> P051126**5**54**A**
> P051126**6**54**B**

4th digit has the strange *2 again:

> P05109**2**067**Y**
> P05109**3**067**A**
> P05109**4**067**C**
> P05109**5**067**G**
> P05109**6**067**I**
> P05109**7**067**K**
> P05109**9**067**O**

5th digit seems regular again:

> P0519**0**2053**D**
> P0519**1**2053**E**
> P0519**2**2053**F**
> P0519**3**2053**G**

6th digit strange again:

> P051**3**99934**S**
> P051**5**99934**Y**
> P051**6**99934**A**
> P051**7**99934**C**
> P051**8**99934**E**

7th digit seems regular again:

> A00**1**395263**W**
> A00**2**395263**X**
> A00**3**395263**Y**
> A00**4**395263**Z**
> A00**5**395263**A**

The last (first) two digits are pretty difficult to check because I couldn't find consecutive numbers easily (but it is probably safe to assume the pattern repeats). I'm pretty sure an algorithm must be able to constructed from the above but I haven't found the right numbers yet.

Btw, there appear to be a couple of numbers that do not validate the online check (e.g. P057170514E, A051320913J)

**Comment by unho** [comment]
I haven't been able to find any data on this. All sources point to use the online checker https://itax.kra.go.ke/KRA-Portal/pinChecker.htm

**Comment by arthurdejong** [comment]
I've also been using that online checker (I've been training my math skills ;) ).

I've found a counter-example that more or less makes the existence of an algorithm that is valid for all numbers unlikely:

> P05112423**5M**
> P05112423**6N**
> P05112423**7Z** <- would expect 7O here
> P05112423**8P**
> P05112423**9Q**

So for now, I'm giving up on finding an actual check digit algorithm and while there probably is one I expect there are a sufficiently large number of numbers that are not generated according to that algorithm.

**Comment by unho** [comment]
That's sad. But after all I was not expecting here to be a check character, since there was no reference to it, and some countries just assign a sequential number with no check character to prevent typos.

I am happy that at least we can validate the format.
