### ISSUE TITLE
Where can I add code related to Pakistan ID card validation?

### ISSUE THREAD

**Issue by QuantumNovice** [arthurdejong/python-stdnum#304]
Please guide me through the process of pushing ID card check for Pakistani ID card. 
I am not familiar with the code base.

**Comment by arthurdejong** [comment]
Hi. It would be great if you could contribute checking of the Pakistani ID card number. I would expect this to end up in `stdnum/pk/idcard.py`. All modules have a more or less similar implementation so have a look at some of the other modules and it should be pretty clear how to add a new format.

What is important for a new format is a reference to some kind of official description of the number (even if it is not in English). This should end up in the module documentation. Another important aspect is tests.Ideally there is a large test set of valid numbers that is shown to be correctly validated (this is sometimes more difficult with personal numbers).
