### ISSUE TITLE
Unclosed file warning

### ISSUE THREAD

**Issue by camux** [arthurdejong/python-stdnum#33]
Running about ubuntu 16.04, python 3.5, i get this warning:

/home/psk/.virtualenvs/tryton40/lib/python3.5/site-packages/stdnum/numdb.py:202:
ResourceWarning: unclosed file <_io.BufferedReader name='/home/psk/.virtualenvs/tryton40/lib/python3.5/site-packages/stdnum/iban.dat'>
  db = read(reader(resource_stream(__name__, name + '.dat')))

**Comment by arthurdejong** [comment]
Thanks for pointing this out. Fixed in 2126947.
