### ISSUE TITLE
IBAN Validation fails on Burundi, Djibouti, Russia, Somalia and Sudan

### ISSUE THREAD

**Issue by rbetancourt27** [arthurdejong/python-stdnum#399]
I'm using stdnum to validate IBAN in my own repo so to test it before going on production I make some tests with a list of IBANs from this [site](https://www.iban.com/structure): from this list I got 83 countries which 5 of them failed on testing. Is this expected? I tried other ways to validate these IBANs and are correct. My code is something like this:

```python
from stdnum.iban import is_valid
# For example in this case a failing number would be DJ2110002010010409943020008
def test(self, number):
  assert is_valid(number=number, check_country=True)

**Comment by arthurdejong** [comment]
The DJ2110002010010409943020008 example seems to work fine:

    >>> from stdnum import iban
    >>> iban.validate('DJ2110002010010409943020008')
    'DJ2110002010010409943020008'

Note that the DJ country code was only added to [the IBAN registry](https://www.swift.com/standards/data-standards/iban-international-bank-account-number) last year and is only part of the 1.18 release of python-stdnum (see ee9dfdf).

**Comment by rbetancourt27** [comment]
Updating my project to the latest version of python-stdnum got resolved for all countries except Somalia which is expected because I don't find it on [IBAN registry](https://www.swift.com/standards/data-standards/iban-international-bank-account-number) and Burundi specifically I tried this IBANs: BI43220001131012345678912345 and SO061000001123123456789

**Comment by DimitriPapadopoulos** [comment]
I do find Somalia (SO) in the current Release 93 – February 2023 of the [IBAN Registry](https://www.swift.com/standards/data-standards/iban-international-bank-account-number).

**Comment by DimitriPapadopoulos** [comment]
Note that these IBAN numbers are invalid according to [IBAN Checker](https://bank.codes/iban/validate/):
```
BI43220001131012345678912345
DJ2110002010010409943020008
SO061000001123123456789
```

**Comment by rbetancourt27** [comment]
> Note that these IBAN numbers are invalid according to [IBAN Checker](https://bank.codes/iban/validate/) or [IBAN Calculator](https://www.ibancalculator.com/) (“_The checksum is incorrect._”):
> 
> ```
> BI43220001131012345678912345
> DJ2110002010010409943020008
> SO061000001123123456789
> ```
> 
> They're probably not up-to-date either, or might use python-stdnum smile
> 
> However, the [official IBAN Checker](https://www.iban.com/iban-checker) does flag the Burundi IBAN (only) as incorrect (“_IBAN Length is incorrect!_”):
> 
> ```
> BI43220001131012345678912345
> ```

Thanks!
