### ISSUE TITLE
AttributeError: module 'stdnum' has no attribute 'ca'

### ISSUE THREAD

**Issue by RushikSantoki** [arthurdejong/python-stdnum#400]
I am trying to use 

**stdnum.ca.sin.validate()**

For which I am getting an error 
**AttributeError: module 'stdnum' has no attribute 'ca'**

It is not able to find reference 'ca' in '__init__.py', says the suggestion.

Following is the code I am implementing: 

```
import stdnum
import random


def GenerateSin():
     numbers = random.randrange(100000000, 999999999)
     return numbers


def ValidateSin():
    tempsin=0
    while not std.ca.sin.valifate(tempsin):
        tempsin = GenerateSin()

    return tempsin


numbersin = ValidateSin()
print(number)
```

**Comment by DimitriPapadopoulos** [comment]
```python
>>> import stdnum.ca.sin
>>> 
>>> stdnum.ca.sin.validate
<function validate at 0x7f0fa1fd8dc0>
>>> 
```

**Comment by arthurdejong** [comment]
Closing this now since the issue has been answered. It is probably not a good idea for python-stdnum to make all modules available through the toplevel module name because of performance reasons (all the modules would have to be loaded for simply an `import stdnum` statement).
