### ISSUE TITLE
DeprecationWarning: pkg_resources is deprecated as an API

### ISSUE THREAD

**Issue by JiriKr** [arthurdejong/python-stdnum#412]
It can be replaced with https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources .

Migration guide is available on https://importlib-resources.readthedocs.io/en/latest/migration.html .

**Comment by arthurdejong** [comment]
Hi @JiriKr,

Thanks for the report and related fix. I don't see the deprecation warning when running the tests. Do you have an easy way to reproduce the warnings? Also, do you know why pkg_resources is deprecated?

**Comment by pulse-mind** [comment]
Hi, Same deprecation on my side.
