### ISSUE TITLE
Implement CBU (unique bank code) of Argentina

### ISSUE THREAD

**Issue by lukio** [arthurdejong/python-stdnum#43]
CBU it s a code of the Banks of Argentina to identify the accounts of their clients.

More information:
https://es.wikipedia.org/wiki/Clave_Bancaria_Uniforme

php library that validate cbu: 
https://github.com/pablorsk/cbu-validator-php

js library that validate cbu:
https://gist.github.com/delucas/4526176

**Comment by arthurdejong** [comment]
Thanks for your report and pull request. I've merged your commits with a few changes (see pull request).

If you have any more numbers that you would like, feel free to create issues or pull requests.

Thanks.
