### ISSUE TITLE
Add support for new Indonesian (NPWP) VAT

### ISSUE THREAD

**Issue by Smolations** [arthurdejong/python-stdnum#432]
Here's [one of several sources](https://www.grantthornton.co.id/insights/global-insights1/updates-regarding-the-format-of-indonesian-tax-id-numbers/) indicating that a new mandatory Indonesian NPWP will soon be the standard (mid-2024). Just a heads up. 😎

**Comment by arthurdejong** [comment]
Thanks for the notification. I added support for the NIK in 5aeaeff and extended the NPWP check to support either the NIK or a 16 digit format with a leading 0 (the 15 digit format is also still accepted).
