### ISSUE TITLE
Correct French VATIN raising error

### ISSUE THREAD

**Issue by JffCosta** [arthurdejong/python-stdnum#434]
Correct french vat according to https://ec.europa.eu/taxation_customs/tin/#/check-tin is raising an error. The vat is: FR3039235943079

**Comment by arthurdejong** [comment]
That service only has very limited validation of the structure of the number (probably limited to a regex). The [EU VIES validation][(url)](https://ec.europa.eu/taxation_customs/vies/) does mark the supplied number as invalid.

The python-stdnum module tries to do extensive checks based on the structure of the number. In case of the French VAT number, it may be a SIREN (which use a Luhn check digit) prefixed with mod 97 or mod 11 check digits. This is not captured in a regex-like check.
