### ISSUE TITLE
Missed inv(checksum)

### ISSUE THREAD

**Issue by seriyvolk83** [arthurdejong/python-stdnum#456]
https://github.com/arthurdejong/python-stdnum/blob/dc850d6c8cc62bcdd88ef5e804f0c86381b97c11/stdnum/verhoeff.py#L113

At the end of the calculation of the new checksum, you need to apply inv(c) function (see https://en.wikipedia.org/wiki/Verhoeff_algorithm )

```
inv = [0, 4, 3, 2, 1, 5, 6, 7, 8, 9]
```

Write unit tests please. 

Check sum for `0241144346` -> 1

**Comment by arthurdejong** [comment]
I've added more tests in 051e63f and I'm pretty sure the implementation in python-stdnum is correct.

If I understand correctly you say that `0241144346` should result in a checksum of 1. I'm pretty sure the check digit should be 1, not the check sum:

    >>> verhoeff.is_valid('0241144346')
    False
    >>> verhoeff.checksum('0241144346')
    7
    >>> verhoeff.calc_check_digit('0241144346')
    '1'
    >>> verhoeff.checksum('02411443461')
    0

If I misunderstood, please clarify.
