### ISSUE TITLE
TIN number from Monaco

### ISSUE THREAD

**Issue by nim-odoo** [arthurdejong/python-stdnum#46]
Hello,

We are facing an issue with the validation of the following TIN numbers: FR40000066034, FR26000040583, FR28000113851 (more to be found at http://www.monaco-directory.com/)...
The number starts with FR, but is for a company in Monaco. You might already know the Monaco uses the French TIN structure.
Note that these numbers are valid according to VIES: http://ec.europa.eu/taxation_customs/vies/

However, the 9 last digits (SIREN number in France) do not pass the Luhn validity check. There doesn't seem to be any issue with the algorithm implemented in stdnum, since other external services don't validate this number either.

At this point, we couldn't find any resource specifying that this number should not verify the Luhn algorithm, the only known exception being La Poste (https://fr.wikipedia.org/wiki/Formule_de_Luhn#Cas_particulier). However, my hypothesis is that it is not the case for Monaco (at least for recent numbers).

Have you heard about this issue before?

Thanks

**Comment by arthurdejong** [comment]
I don't think I investigated the Monaco situation before but I understand that they are indeed use French numbers in one way or another.

Interestingly the first number you provided is invalid according to
  https://ec.europa.eu/taxation_customs/tin/tinRequest.html
but valid according to
  http://ec.europa.eu/taxation_customs/vies/
but also not found via
  http://www.sirene.fr/sirene/public/recherche

This leads me to believe there is some special casing going on and the numbers are not considered a valid French SIREN but a valid VAT number nonetheless. Note that the numbers all do have correct first two digits (part of the TVA).

I selected a few numbers at random from the directory you provided and the only pattern I could find was that they all have four zero digits after the two check digits. If this is indeed the correct, the validation could be extended to only do the SIREN validation if the first 4 digits are not zero.

**Comment by nim-odoo** [comment]
Hello,

Thanks for the reply. That was also the conclusion we reached.

> I could find was that they all have four zero digits after the two check digits. If this is indeed the correct, the validation could be extended to only do the SIREN validation if the first 4 digits are not zero.

This is not the case for FR28000113851, for example. My assumption is that Monaco simply increments the 9 digits available, without any specific checksum to verify. However, I don't any resource that confirms this.

I'm unsure about the strategy to apply. If the SIREN validation is performed only if the first 3 (or 4) digits are not zero, I guess there might be a chance to validate incorrect numbers. However, I guess the probability should be quite small.

**Comment by arthurdejong** [comment]
I have implemented the extra checking in c957318. For now, if the first twee digits after the check digits are all zero it is assumed to be a Monaco VAT number and the SIREN validation is not done.

I have tested this with a couple of numbers from the Monaco directory and all numbers either validate or are also not considered valid by the VIEW online check.

**Comment by nim-odoo** [comment]
Thanks a lot!
