### ISSUE TITLE
[do] rnc: validation confirmation

### ISSUE THREAD

**Issue by gustavovalverde** [arthurdejong/python-stdnum#47]
Hi, I'm from Dominican Republic.

I'm trying to understand the logic under this validation:
https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/do/rnc.py#L53

As I'm getting 31,000 more exceptions in RNC validation using this logic, but I can't figure out what it's actually doing.

**Comment by arthurdejong** [comment]
The function is used for the check digit calculation. The last line turns the sum that is calculated into a check digit.

Line 52 calculates the weighted sum modulo 11. Line 53 translates the sum into a single digit:
`{0: 2, 1: 1, 2: 9, 3: 8, 4: 7, 5: 6, 6: 5, 7: 4, 8: 3, 9: 2, 10: 1}`
The following line should be equivalent:
`return '21987654321'[check]`

If you have access to RNC numbers that should be valid but are not validated by python-stdnum I would like to know.

It could be that there is a bug in python-stdnum and if that is the case I would like to fix it. It could also be that official numbers are assigned that do no match the check digit algorithm. If that is the case the python-stdnum should be modified to allow skipping the check digit validation for these numbers or perhaps even disable check digit validation by default (e.g. as was done for the Mexican RFC).

**Comment by gustavovalverde** [comment]
I know everything else is OK. 

I'm just curious about the `str((10 - check) % 9 + 1)`, which I'm far as I've realized it's the `check_digit`. But I've commonly seem this approach for the RNC:
```
    if check == 0:
        check_digit = 2
    if check == 1:
        check_digit = 1
    else:
        check_digit = 11 - result
```
With `str((10 - check) % 9 + 1)` the first and second condition is happening, but I'm not sure about the third.

**Comment by arthurdejong** [comment]
Since the check value is in the range 0..10 (or range(11) in Python) you can easily test that they are equivalent:
```
>>> [(10 - check) % 9 + 1 for check in range(11)]
[2, 1, 9, 8, 7, 6, 5, 4, 3, 2, 1]
>>> def func(check):
...     if check == 0:
...         return 2
...     if check == 1:
...         return 1
...     else:
...         return 11 - check
... 
>>> [func(check) for check in range(11)]
[2, 1, 9, 8, 7, 6, 5, 4, 3, 2, 1]
```

I personally prefer the more functional approach to these algorithms over the imperative approach so that is why most check digit implementations in stdnum are implemented in this way.

**Comment by gustavovalverde** [comment]
Thanks for the clarification, I really appreciate it ;)

BTW, here's an already implemented approach to test against the regulator who validates the RNCs and Cedulas: https://github.com/developersdo/dgii-consultas/tree/master/consulta-dgii-python

Here's their WebServices, but no one has yet implemented their solution using it, as it's very new: http://www.dgii.gov.do/wsMovilDGII/WSMovilDGII.asmx

Just in case you'd like to add this to your online_check

**Comment by gustavovalverde** [comment]
@arthurdejong I'd like to fund a development from your side, so you could also add Dominican Republic for online validation.

**Comment by arthurdejong** [comment]
Hi @gustavovalverde,
I'd love to develop this feature in python-stdnum. Please contact me by email (arthur@arthurdejong.org) for specifics.
If it concerns using the online service you mentioned earlier to add lookups in python-stdnum that should not be too difficult.
