### ISSUE TITLE
Czech VAT number marked as invalid, but OK in VIES

### ISSUE THREAD

**Issue by andreparames** [arthurdejong/python-stdnum#51]
Hi, first of all thanks for maintaining an invaluable library that is underappreciated.

The problem I'm having is with the VAT number CZ 682127228, which stdnum reports as invalid but VIES says is OK, and even returns info about its registrant. Curiously, the number used as an example of the special case in the documentation ("640903926") is considered invalid by VIES.

Unfortunately, I was unable to find the official formula for verifying Czech VAT numbers.

**Comment by arthurdejong** [comment]
Thanks for reporting this. I have just pushed a commit that should fix this issue. There was a bug in the check digit calculation (specifically if the check digit should be 8).

Some of the check digit algorithms are carefully hidden but the European formats are now published by the European commission on https://ec.europa.eu/taxation_customs/tin/ (the FS-TIN Algorithms-Public document linked at the bottom).

I will prepare a release to PyPI that fixes this issue in the coming days.

**Comment by andreparames** [comment]
@arthurdejong thank you! I wish paid services had this speedy response!
