### ISSUE TITLE
[stdnum.do] check_dgii has to be implemented for cedula

### ISSUE THREAD

**Issue by gustavovalverde** [arthurdejong/python-stdnum#63]
The webservice of the DGII not just validates RNC, but also the Cedula, and this is needed to get the information from persons that also have fiscal identifications with the regulator.

**Comment by arthurdejong** [comment]
You should already be able to use the RNC implementation of check_dgii() for validating a Cedula. I will look into also putting this function in the cedula namespace.

**Comment by gustavovalverde** [comment]
Mmm, you're actually right. My bad, I thought that the check_dgii() on RNC implementation was also validating the number formatting.

I'll give it a try, this could be an enhancement for later.
