### ISSUE TITLE
Belgian IBAN number ending in 00

### ISSUE THREAD

**Issue by Autom3** [arthurdejong/python-stdnum#70]
Apparently Belgian (and maybe also other country's) IBAN numbers should not end in 00.

Example: BE543101002700**00**
But should actually BE543101002700**97**

According to https://www.ibancalculator.com/iban_validieren.html the IBAN ending in 00 is invalid and 97 is valid.

**Comment by arthurdejong** [comment]
This should already be covered in the current code (at least since python-stdnum 1.5):

    >>> iban.validate('BE54310100270097')
    'BE54310100270097'
    >>> iban.validate('BE54310100270000')
    Traceback (most recent call last):
        ...
    InvalidChecksum: ...

Am I missing something?

**Comment by Autom3** [comment]
Ah you are right, I was just using an older version from pipy. My bad!

**Comment by Autom3** [comment]
I just wanted to let you know that it does seem like I am on a version 1.8.1, and on that version it is still making the mistake (is there a new version on pypi in sight any time soon?)

```
$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from stdnum import iban
>>> iban
<module 'stdnum.iban' from '/usr/local/lib/python3.5/dist-packages/stdnum/iban.py'>
>>> iban.validate('BE54310100270097')
'BE54310100270097'
>>> iban.validate('BE54310100270000')
'BE54310100270000'
>>>
```
```
$ tail -1 /usr/local/lib/python3.5/dist-packages/stdnum/__init__.py 
__version__ = '1.8.1'
```

For now I will just clone and setup, that seems to work :+1:
