### ISSUE TITLE
[1.9] stdnum.do: Not validating NCF on with DGII's WebService 

### ISSUE THREAD

**Issue by gustavovalverde** [arthurdejong/python-stdnum#71]
It seems that the regulator deprecated this validation from their SOAP WebService; now the only available method to do this validation is using this tool (manually):

http://www.dgii.gov.do/servicios/consultas/Paginas/ConsultaNCF.aspx

@arthurdejong If you could please have a look at this tool and let us know if it's possible to have this integrated into stdnum. This needs a different technique (scraping), which I don't know if it's under stdnum's approach to get information.

Let me know if this is possible.

**Comment by arthurdejong** [comment]
If I understand correctly the SOAP service still works but does not support the new format for NCF. It seems the other validation and the validation of old format NCF still work.
Do you have a reference explaining the status of the SOAP service?
I've had a look at the form but it indeed looks like it requires some screen scraping. It also requires passing a few hard-coded blobs in the request and I wouldn't be surprised if these blobs regularly change which makes this difficult to support.
In any case I've got the making of a request working (the result evaluation and information extraction remains to be done):

    def check_dgii_form(rnc, ncf, timeout=30):
        import requests
        url = 'http://www.dgii.gov.do/app/WebApps/ConsultasWeb/consultas/ncf.aspx'
        headers = {
            'User-Agent': 'Mozilla/5.0 (python-stdnum)',
        }
        data = {
            '__ASYNCPOST': 'true',
            '__EVENTVALIDATION': '/wEWBAKh8pDuCgK+9LSUBQLfnOXIDAKErv7SBhjZB34//pbvvJzrbkFCGGPRElcd',
            '__VIEWSTATE': '/wEPDwUJNTM1NDc0MDQ5ZGRCFUYoDcVRgzEntcKfSuvPnC2VhA==',
            'ctl00$cphMain$btnConsultar': 'Consultar',
            'ctl00$cphMain$txtNCF': ncf,
            'ctl00$cphMain$txtRNC': rnc,
        }
        return requests.post(url, headers=headers, data=data, timeout=timeout)

**Comment by gustavovalverde** [comment]
Actually, I did not explain it correctly. Yes; old NCF are validated, new ones are not. Also Cedulas and RNC are still working with the service.

SOAP Service status for new NCF: **Unknown**  (who built it is no longer there)  <-- 3rd world problems.

**Comment by arthurdejong** [comment]
Note that the implementation I pushed is a best-effort attempt to perform this test. It is very fragile so I'm not sure how future-proof this is. ;)
