### ISSUE TITLE
Norwegian bank account numbers?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arthurdejong/python-stdnum#79]
Hi.

What would need to be done to get functions to verify Norwegian bank account numbers into stdnum?  https://www.ecbs.org/iban/norway-bank-account-number.html and https://metacpan.org/source/GAAS/Norge-1.08/No/KontoNr.pm have details on how to verify them.

**Comment by arthurdejong** [comment]
The perl implementation and references should be sufficient in terms of code I think. What I need is a suggested name for the module. Would stdnum.no.kontonr be appropriate?

Some countries are switching to using the IBAN as primary bank account number identifier. If Norway is moving to using the IBAN I could only make a stdnum.no.iban. Otherwise the native number module would get a to_iban() function (similar to how the Spanish [ccc](https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/es/ccc.py#L121) and [iban](https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/es/iban.py#L59) modules are implemented).

Do you know if there is some kind of registry that maps the first 4 digits to banks? For Belgian IBANs [this is available](https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/be/banks.dat) and it allows for [some extra validation](https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/be/iban.py#L89).

Other than that it would be helpful to have a short blurb for the module docstring and perhaps some test numbers (though with Google it is reasonably easy to build a list of Norwegian IBANs).

**Comment by petterreinholdtsen** [comment]
[Arthur de Jong]
> The perl implementation and references should be sufficient in terms
> of code I think. What I need is a suggested name for the module. Would
> stdnum.no.kontonr be appropriate?

Yes, I believe kontonr would work.  It translates to account number.
Might be a bit generic, though, as it could be any kind of account.
What about 'bankkonto'?

> Some countries are switching to using the IBAN as primary bank account
> number identifier. If Norway is moving to using the IBAN I could only
> make a stdnum.no.iban. Otherwise the native number module would get a
> to_iban() function (similar to how the Spanish
> [ccc](https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/es/ccc.py#L121)
> and
> [iban](https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/es/iban.py#L59)
> modules are implemented).

I'm not aware of any effort here in Norway to move to IBAN for internal
use.

> Do you know if there is some kind of registry that maps the first 4
> digits to banks? For Belgian IBANs [this is
> available](https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/be/banks.dat)
> and it allows for [some extra
> validation](https://github.com/arthurdejong/python-stdnum/blob/master/stdnum/be/iban.py#L89).

I had a look, and the official registry is available for those that are
willing to pay from
<URL: https://www.finansnorge.no/om-finans-norge/publikasjoner/bankplassregisteret/ >.

I could not find any public and non-restricted list of bank registry
numbers.  I notice Denmark have <URL: http://banker.multitrading.dk/ >,
but could not find anything similar when searching for a Norwegian
public list.

> Other than that it would be helpful to have a short blurb for the
> module docstring and perhaps some test numbers (though with Google it
> is reasonably easy to build a list of Norwegian IBANs).

Here are two test numbers.

  # Norges Røde kors, https://www.rodekors.no/stott-arbeidet/
  '8200 06 10190',
  # Flykningehjelpen, https://www.flyktninghjelpen.no/hjelp-mennesker-pa-flukt/
  '8380.08.06006',

I sketched some code to verify bank account numbers, based on the perl
module.  Here is the draft code.  Let me know if you want me to
relisence.

# -*- coding: utf-8 -*-
# Copyright (c) 2018 Petter Reinholdtsen <pere@hungry.com>
# This file is covered by the GPLv2 or later, read COPYING for details.

# Based on https://metacpan.org/source/GAAS/Norge-1.08/No/KontoNr.pm
# FIXME Should consider adding Norwegian account checking code to
# https://github.com/arthurdejong/python-stdnum/

import re
import stdnum.util

def mod10(n):
    sum = 0
    factor = 2 # factor switch betweeen 2 and 1
    for s in n[::-1]:
        p = int(s) * factor
        if p >= 10:
            sum = sum - 1
            p = p - 10
        sum = sum - p
        factor = 3 - factor
    return sum % 10

def mod11(n):
    """Calculate modulo 11 checksum of the string n with the digits of
the number to calculate the checksum for.

    """
    digits = n[::-1]
    sum = 0
    factors = list(range(2, 8)) * (int(len(digits)-1/6)+1)
    for d in digits:
        sum = sum - int(d) * factors.pop(0)
    k = sum % 11
    if 10 == k:
        return None
    return k

def no_bank_compact(number):
    """Convert the number to the minimal representation. This strips the
    number of any valid separators and removes surrounding whitespace."""
    return stdnum.util.clean(number, ' .').strip()

def verifyNorwegianBankAccount(account):
    if account is None:
        return False

    account = no_bank_compact(account)

    # Only accept digits
    if re.match(r"[0-9]+$", account) is None:
        return False

    checksum = int(account[-1])

    # Replace 0000.XX.XXXXX with XX.XXXXX
    if account.startswith('0000'):
        account = accounts[4:]

    if (7 == len(account)):
        check = mod10(account[0:-1])
    elif (11 == len(account)):
        check = mod11(account[0:-1])
    else:
        return False # invalid length

    if check is None or check != checksum:
        return False
    return True

-- 
Happy hacking
Petter Reinholdtsen

**Comment by arthurdejong** [comment]
Do you happen to have some examples of either the 7 digit numbers or the numbers that start with 0000 (those are apparently for the postgiro)? I couldn't find any online easily.

**Comment by petterreinholdtsen** [comment]
[Arthur de Jong]
> Do you happen to have some examples of either the 7 digit numbers or
> the numbers that start with 0000 (those are apparently for the
> postgiro)? I couldn't find any online easily.

Not really.  Have not seen any of those in years.

I did a search for "postgironummer", and came across "5 91 60 77" "17 65
81-7", "2 30 07 21", "2 10 62 19" and "2 36 87 85".  I did not check if
they are valid numbers, though. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
Thank you very much!
