### ISSUE TITLE
Validate Bitcoin addresses?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arthurdejong/python-stdnum#80]
Hi.  Would it be interesting to add code to validate bitcoin addresses in this library?  It would be useful when asking users to provide a bitcoin address in a web application.

I do not know how to properly validate them myself, but see that valid length of a BTC is 26 to 35 characters, according to https://en.bitcoin.it/wiki/Address, while https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#Reference_implementations shows 42 character long addresses. A complicating factor is Lightning addresses explained in https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md .

**Comment by arthurdejong** [comment]
Sounds like a good idea! The pointers you gave should be sufficient to make the implementation.

**Comment by petterreinholdtsen** [comment]
[Arthur de Jong]k <notifications@github.com> writes:
> Sounds like a good idea! The pointers you gave should be sufficient to
> make the implementation.

Great.  If you want a set of valid test addresses, here is a short list
based on various publiched sources:

  1NEDqZPvTWRaoho48qXuLLsrYomMXPABfD
  1P2c1W3x1TCUFvyDmVyVmUxrRqFtuF2w6
  39y1UjCMmxzMYtt4S4wii9e3xmfHngKncL
  3KwLBFMtU9Wtn9Yys3imuU2hs2oSDsfZY4
  bc1q362mcakh9p0zr380s4uhhz26263yjep36c8se8
  bc1qardv855yjngspvxuttq897aqca3lxju2y69jce

I no longer rememeber where I found them. :)

-- 
Happy hacking
Petter Reinholdtsen
