### ISSUE TITLE
IBAN check for experimental IBAN countries / unimplemented country exception?

### ISSUE THREAD

**Issue by AndrejZbin** [arthurdejong/python-stdnum#82]
https://www.iban.com/structure
I would like to like to let users enter IBANs of experimental IBAN countries into my application too, or If a country doesn't use IBANs, let him use other formats. Currently, it's not possible to detect, whether entered IBAN is invalid, or the country is not implemented.

Perhaps it would be better to return new exception (InvalidCountry) when info[0][1].get('bban', '') returns nothing instead of raising InvalidFormat?

**Comment by arthurdejong** [comment]
I can probably raise `InvalidComponent` if the country code is not found which is probably more correct. That would mean that the mod 97,10 checksum is validated but nothing else. Would that be helpful?

**Comment by AndrejZbin** [comment]
Yes, that sounds good @arthurdejong
