### ISSUE TITLE
DNI as Argentinian ID number

### ISSUE THREAD

**Issue by mariomop** [arthurdejong/python-stdnum#90]
Hi,
Do you think that for Argentina we could add validation for [DNI](https://en.wikipedia.org/wiki/Documento_Nacional_de_Identidad_(Argentina))?
DNI numbers are used to identify physical people in Argentina, but the only thing we have to validate is that there are no letters, and that the number has 7 or 8 digits at least.
Best

**Comment by arthurdejong** [comment]
I have added a validation function for this even though the validation is really simple. Thanks for pointing this out.
