### ISSUE TITLE
Add related packages to documentation

### ISSUE THREAD

**Issue by PanderMusubi** [arthurdejong/python-stdnum#91]
Please, add related packages to documentation, such as:
* https://pypi.org/project/phonenumbers/ and/or https://github.com/daviddrysdale/python-phonenumbers
* https://pypi.org/project/pycountry/ and/or https://bitbucket.org/flyingcircus/pycountry
* https://pypi.org/project/roman/ and/or https://github.com/zopefoundation/roman

**Comment by PanderMusubi** [comment]
Understandable. However, these are all well-maintained and don't overlap with python-stdnum. There are indeed a lot of other packages out there, but are usually stale or provide only a subset of the functionality. Otherwise close this issue and use it for reference when people ask regarding functionality related to these packages.

**Comment by arthurdejong** [comment]
Closing this issue as suggested. This will not be fixed any time soon and I would like to prioritise getting more formats in python-stdnum.
