### ISSUE TITLE
Support mac addresses

### ISSUE THREAD

**Issue by PanderMusubi** [arthurdejong/python-stdnum#93]
Support lookup of vendor and model for a mac address. Data is available under https://github.com/aaronjwood/PortAuthority/issues/84 but best is to contact the author. He has made a FOSS collection, especially for these purposes. This service can be called via the API or can be included. Best to ask him.

**Comment by arthurdejong** [comment]
There is already [a netaddr package](https://pypi.org/project/netaddr/) that seems to do MAC address validation. The only downside of that package, as far as I can see, is that it has not been updated for 2 years (and the release before that was almost 3,5 years ago).
