### ISSUE TITLE
LV birthdate parser failed

### ISSUE THREAD

**Issue by Totorokrut** [arthurdejong/python-stdnum#94]
Example with LV personal code:

> In [27]: stdnum.lv.pvn.get_birth_date('200390-11718')
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-27-b2e61c42e997> in <module>()
> ----> 1 stdnum.lv.pvn.get_birth_date('200390-11718')
> 
> /.../lib/python2.7/site-packages/stdnum/lv/pvn.pyc in get_birth_date(number)
>      80     day = int(number[0:2])
>      81     month = int(number[2:4])
> ---> 82     year = int(number[4:6])
>      83     year += 1800 + int(number[6]) * 100
>      84     try:
> 
> ValueError: invalid literal for int() with base 10: '-'

The reason is '-'. Probably `number = compact(number)` can help if put it on 1st line in this function to replace '-'.

**Comment by arthurdejong** [comment]
Thanks for pointing this out. This (and the same problem in a few other modules) has been fixed in 4cb44aa.
