### ISSUE TITLE
Add Turkish VAT number validation

### ISSUE THREAD

**Issue by unho** [arthurdejong/python-stdnum#99]
Or steal it from Odoo: https://github.com/odoo/odoo/blob/master/addons/base_vat/models/res_partner.py#L351-L392

**Comment by unho** [comment]
This seems to have been already implemented.

**Comment by arthurdejong** [comment]
The [T.C. Kimlik No.](https://arthurdejong.org/python-stdnum/doc/1.11/stdnum.tr.tckimlik) has been implemented (which is for individuals) but the Vergi Kimlik Numarası (which seems to be for companies) has not yet been implemented.

**Comment by unho** [comment]
My apologies.

**Comment by arthurdejong** [comment]
No apologies needed :) Always happy to look into new formats. I have a long list of formats that I could implement and always looking into which number is best to implement next.
